# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('leave_type', models.CharField(choices=[('Annual Leave', 'Annual Leave'), ('Sick Leave', 'Sick Leave'), ('Family Responsibility Leave', 'Family Responsibility Leave'), ('Study Leave', 'Study Leave')], max_length=22)),
                ('status', models.CharField(choices=[('New', 'New'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled')], max_length=22)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('approved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
